# Generated by Django 5.1.7 on 2025-08-09 05:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_competition_close_registration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_looking_for_members',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='close_registration',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 16, 5, 15, 9, 894938, tzinfo=datetime.timezone.utc)),
        ),
    ]
