# Generated by Django 5.1.7 on 2025-08-09 17:12

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_team_is_looking_for_members_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='api.team'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='close_registration',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 16, 17, 12, 44, 294567, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='registration',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='api.competition'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together={('competition', 'user')},
        ),
    ]
