# Generated by Django 5.1.7 on 2025-08-09 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_competition_close_registration_teaminvite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teaminvite',
            name='accepted',
        ),
        migrations.AddField(
            model_name='teaminvite',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='competition',
            name='close_registration',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 16, 17, 50, 19, 157097, tzinfo=datetime.timezone.utc)),
        ),
    ]
