# Generated by Django 5.1.7 on 2025-08-09 18:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_teaminvite_accepted_teaminvite_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teaminvite',
            name='status',
        ),
        migrations.AddField(
            model_name='teaminvite',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='competition',
            name='close_registration',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 16, 18, 40, 39, 991634, tzinfo=datetime.timezone.utc)),
        ),
    ]
