# Generated by Django 5.1.7 on 2025-08-09 20:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_teaminvite_status_teaminvite_accepted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='close_registration',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 16, 20, 41, 32, 856288, tzinfo=datetime.timezone.utc)),
        ),
    ]
