# Generated by Django 5.1.7 on 2025-08-09 20:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_competition_close_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='close_registration',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 16, 20, 55, 20, 64892, tzinfo=datetime.timezone.utc)),
        ),
    ]
