# Generated by Django 5.1.7 on 2025-08-10 21:37

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_competition_close_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='competition',
            name='close_registration',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 17, 21, 37, 57, 121692, tzinfo=datetime.timezone.utc)),
        ),
    ]
